### test

GET https://google.com HTTP/1.1


### test3

GET https://prdpeuwst125268dcon01.blob.core.windows.net/data-connect-cases?restype=container&comp=list&sv=2024-11-04&ss=bf&srt=sco&sp=rltfx&se=2026-06-19T02:57:58Z&st=2025-06-18T18:57:58Z&spr=https&sig=2ouCOsbSSLNS9Ft9fXguaqPbfwFacCVQhGFbahvHigw%3D HTTP/1.1


### test4

GET https://dtpprdstinputs.blob.core.windows.net/datavision?restype=container&comp=list&si=datavision-source-write&spr=https&sv=2024-11-04&sr=c&sig=qwWdwt8aJbLrMZZ%2FqwKUHCXhCvw%2BBioeUYZTyJXfKxo%3D HTTP/1.1
